### ISSUE TITLE
Ability to use a secrets manager secret to set the master password

### ISSUE THREAD

**Issue by ptmclean** [cfn-modules/rds-aurora-serverless#5]
This is a feature request rather than an issue. 

I'd like t o be able to use secrets manager to manage my secrets rather than specify the master password directly in cloudformation source code. 

For the stacks I have at the moment I have created a bit of a copy of your projects for an aws secret [here](https://github.com/ptmclean/secret), it's also published [here](https://www.npmjs.com/package/cfn-modules-secret) if you want to try it out.

Then I would like to  be able to use this stack as the provider for the password using something like #4 with code like this...
```
  Key:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        AlertingModule: !GetAtt 'Alerting.Outputs.StackName'
      TemplateURL: './node_modules/@cfn-modules/kms-key/module.yml'
  MySqlMasterPassword:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        KmsKeyModule: !GetAtt 'Key.Outputs.StackName'
        Name: "SQL/Prod/MASTER-PASSWORD"
      TemplateURL: './node_modules/cfn-modules-secret/module.yml'
  AuroraServerlessCluster:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        VpcModule: !GetAtt 'Vpc.Outputs.StackName'
        AlertingModule: !GetAtt 'Alerting.Outputs.StackName'
        ClientSgModule: !GetAtt 'ClientSg.Outputs.StackName'
        KmsKeyModule: !GetAtt 'Key.Outputs.StackName'
        DBName: 'finance_tracker'
        DBMasterUsername: 'master'
        DBMasterUserPasswordSecretModule: !GetAtt 'MySqlMasterPassword.Outputs.StackName'
      TemplateURL: './node_modules/@cfn-modules/rds-aurora-serverless/module.yml'
```

This will probably need some discussion so I guess this is very much a work in progress. If you think it would be a good idea, I would be very happy if the code moves from [here](https://github.com/ptmclean/secret) into this organisation and then a PR to allow it's use in this repo.
